// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBackend(arg1:string):Promise<boolean>;

export function GetRemoteFileTree(arg1:string):Promise<string>;

export function HealthCheck(arg1:string,arg2:number):Promise<string>;

export function InstallBackend(arg1:string):Promise<string>;

export function KillPort(arg1:number):Promise<void>;

export function SaveIdentityFile(arg1:string,arg2:string):Promise<string>;

export function StartTunnel(arg1:string):Promise<string>;

export function StartTunnelWithProfile(arg1:string):Promise<string>;

export function StopTunnel():Promise<string>;

export function TailRemoteLogs(arg1:string):Promise<string>;

export function TunnelStatus():Promise<string>;
