// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBackend(arg1) {
  return window['go']['app']['App']['CheckBackend'](arg1);
}

export function HealthCheck(arg1, arg2) {
  return window['go']['app']['App']['HealthCheck'](arg1, arg2);
}

export function InstallBackend(arg1) {
  return window['go']['app']['App']['InstallBackend'](arg1);
}

export function SaveIdentityFile(arg1, arg2) {
  return window['go']['app']['App']['SaveIdentityFile'](arg1, arg2);
}

export function StartTunnel(arg1) {
  return window['go']['app']['App']['StartTunnel'](arg1);
}

export function StartTunnelWithProfile(arg1) {
  return window['go']['app']['App']['StartTunnelWithProfile'](arg1);
}

export function StopTunnel() {
  return window['go']['app']['App']['StopTunnel']();
}

export function TunnelStatus() {
  return window['go']['app']['App']['TunnelStatus']();
}
