/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * MLCRemote API
 * Lightweight remote development server API.
 * OpenAPI spec version: 0.3.0
 */
export interface HealthInfo {
  status?: string;
  version?: string;
  pid?: number;
  cpu_percent?: number;
  sys_mem_free_bytes?: number;
  /** True if password login is enabled. */
  password_auth?: boolean;
  /** True if an auth token is required for protected endpoints. */
  auth_required?: boolean;
  host?: string;
  os?: string;
  distro?: string;
  start_time?: string;
  timezone?: string;
  sys_mem_total_bytes?: number;
  go_alloc_bytes?: number;
  go_sys_bytes?: number;
  server_time?: string;
}

export interface LoginRequest {
  password?: string;
}

export interface LoginResponse {
  token?: string;
}

export interface VersionInfo {
  backend?: string;
  frontendCompatible?: string;
}

export type SettingsTheme = typeof SettingsTheme[keyof typeof SettingsTheme];


export const SettingsTheme = {
  dark: 'dark',
  light: 'light',
} as const;

export type SettingsUiMode = typeof SettingsUiMode[keyof typeof SettingsUiMode];


export const SettingsUiMode = {
  classic: 'classic',
  modern: 'modern',
} as const;

export interface Settings {
  allowDelete?: boolean;
  defaultShell?: string;
  theme?: SettingsTheme;
  autoOpen?: boolean;
  showHiddenFiles?: boolean;
  hideMemoryUsage?: boolean;
  maxEditorSize?: number;
  uiMode?: SettingsUiMode;
  language?: string;
  onboardingCompleted?: boolean;
}

export interface DirEntry {
  name?: string;
  path?: string;
  isDir?: boolean;
  size?: number;
  modTime?: string;
}

export interface FileStat {
  isDir?: boolean;
  size?: number;
  mode?: string;
  modTime?: string;
  absPath?: string;
  mime?: string;
}

export interface TrashEntry {
  originalPath?: string;
  trashPath?: string;
  deletedAt?: string;
}

export interface RestoreRequest {
  trashPath?: string;
}

export interface TerminalSession {
  id?: string;
}

export type GetApiTreeParams = {
/**
 * Relative path to list (default root)
 */
path?: string;
showHidden?: boolean;
};

export type GetApiFileParams = {
path: string;
};

export type PostApiFileBody = {
  path?: string;
  content?: string;
};

export type DeleteApiFileParams = {
path: string;
};

export type GetApiFileSectionParams = {
path: string;
offset?: number;
length?: number;
};

export type GetApiStatParams = {
path: string;
};

export type PostApiUploadParams = {
/**
 * Target directory
 */
path?: string;
};

export type PostApiUploadBody = {
  file?: string[];
};

export type PostApiTerminalNewParams = {
shell?: string;
cwd?: string;
};

export type GetWsTerminalParams = {
id?: string;
token?: string;
};

