// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CheckBackend(arg1:string):Promise<boolean>;

export function CheckRemoteVersion(arg1:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<boolean>;

export function DeployAgent(arg1:string,arg2:string):Promise<string>;

export function DetectRemoteOS(arg1:string):Promise<string>;

export function GetProfile(arg1:string):Promise<app.ConnectionProfile>;

export function GetRemoteFileTree(arg1:string):Promise<string>;

export function HasMasterPassword():Promise<boolean>;

export function HealthCheck(arg1:string,arg2:number):Promise<string>;

export function InstallBackend(arg1:string):Promise<string>;

export function IsServerRunning(arg1:string,arg2:string):Promise<boolean>;

export function KillPort(arg1:number):Promise<void>;

export function ListProfiles():Promise<Array<app.ConnectionProfile>>;

export function SaveIdentityFile(arg1:string,arg2:string):Promise<string>;

export function SaveProfile(arg1:app.ConnectionProfile):Promise<string>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function StartTunnel(arg1:string):Promise<string>;

export function StartTunnelWithProfile(arg1:string):Promise<string>;

export function StopTunnel():Promise<string>;

export function TailRemoteLogs(arg1:string):Promise<string>;

export function TunnelStatus():Promise<string>;

export function VerifyMasterPassword(arg1:string):Promise<boolean>;
