// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBackend(arg1) {
  return window['go']['app']['App']['CheckBackend'](arg1);
}

export function CheckRemoteVersion(arg1) {
  return window['go']['app']['App']['CheckRemoteVersion'](arg1);
}

export function DeduplicateProfiles() {
  return window['go']['app']['App']['DeduplicateProfiles']();
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DeployAgent(arg1, arg2) {
  return window['go']['app']['App']['DeployAgent'](arg1, arg2);
}

export function DetectRemoteOS(arg1) {
  return window['go']['app']['App']['DetectRemoteOS'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['app']['App']['GetProfile'](arg1);
}

export function GetRemoteFileTree(arg1) {
  return window['go']['app']['App']['GetRemoteFileTree'](arg1);
}

export function HasMasterPassword() {
  return window['go']['app']['App']['HasMasterPassword']();
}

export function HealthCheck(arg1, arg2) {
  return window['go']['app']['App']['HealthCheck'](arg1, arg2);
}

export function InstallBackend(arg1) {
  return window['go']['app']['App']['InstallBackend'](arg1);
}

export function IsServerRunning(arg1, arg2) {
  return window['go']['app']['App']['IsServerRunning'](arg1, arg2);
}

export function KillPort(arg1) {
  return window['go']['app']['App']['KillPort'](arg1);
}

export function ListProfiles() {
  return window['go']['app']['App']['ListProfiles']();
}

export function SaveIdentityFile(arg1, arg2) {
  return window['go']['app']['App']['SaveIdentityFile'](arg1, arg2);
}

export function SaveProfile(arg1) {
  return window['go']['app']['App']['SaveProfile'](arg1);
}

export function SetMasterPassword(arg1) {
  return window['go']['app']['App']['SetMasterPassword'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['app']['App']['StartTunnel'](arg1);
}

export function StartTunnelWithProfile(arg1) {
  return window['go']['app']['App']['StartTunnelWithProfile'](arg1);
}

export function StopTunnel() {
  return window['go']['app']['App']['StopTunnel']();
}

export function TailRemoteLogs(arg1) {
  return window['go']['app']['App']['TailRemoteLogs'](arg1);
}

export function TunnelStatus() {
  return window['go']['app']['App']['TunnelStatus']();
}

export function VerifyMasterPassword(arg1) {
  return window['go']['app']['App']['VerifyMasterPassword'](arg1);
}
