// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function CheckBackend(arg1:string):Promise<boolean>;

export function CheckRemoteVersion(arg1:string):Promise<string>;

export function DeduplicateProfiles():Promise<number>;

export function DeleteProfile(arg1:string):Promise<boolean>;

export function DeployAgent(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeploySSHKey(arg1:app.SSHDeployRequest):Promise<void>;

export function DetectRemoteOS(arg1:string):Promise<string>;

export function GetManagedIdentity():Promise<string>;

export function GetManagedIdentityPath():Promise<string>;

export function GetProfile(arg1:string):Promise<config.ConnectionProfile>;

export function GetRemoteFileTree(arg1:string):Promise<string>;

export function HasMasterPassword():Promise<boolean>;

export function HealthCheck(arg1:string,arg2:string,arg3:number):Promise<string>;

export function InstallBackend(arg1:string):Promise<string>;

export function IsPremium():Promise<boolean>;

export function IsServerRunning(arg1:string,arg2:string):Promise<boolean>;

export function KillPort(arg1:number):Promise<void>;

export function ListProfiles():Promise<Array<config.ConnectionProfile>>;

export function PickIdentityFile():Promise<string>;

export function ProbeConnection(arg1:app.SSHDeployRequest):Promise<string>;

export function SaveIdentityFile(arg1:string,arg2:string):Promise<string>;

export function SaveProfile(arg1:config.ConnectionProfile):Promise<string>;

export function SetMasterPassword(arg1:string):Promise<void>;

export function SetupManagedIdentity(arg1:app.SSHDeployRequest):Promise<string>;

export function StartTunnel(arg1:string):Promise<string>;

export function StartTunnelWithProfile(arg1:string):Promise<string>;

export function StopTunnel():Promise<string>;

export function TailRemoteLogs(arg1:string):Promise<string>;

export function TunnelStatus():Promise<string>;

export function VerifyMasterPassword(arg1:string):Promise<boolean>;

export function VerifyPassword(arg1:app.SSHDeployRequest):Promise<string>;
