// Generated file: icons.tsx
// Project: mlcremote (https://github.com/mlechner911/mlcremote)
// Do not edit this file — it is generated by cmd/icon-gen
// Generated: 2026-01-17T07:16:30Z

import React from 'react'
import type { IconExtKey, IconMimeKey } from './icons-types'
export type IconProps = { name?: string; className?: string; title?: string; size?: number }
export const Icon: React.FC<IconProps> = ({ name, className, title, size = 16 }) => {
  if (!name) return null
  const href = `#${name}`
  return (
    <svg className={className} width={size} height={size} aria-hidden={title? undefined : 'true'} role={title? 'img' : undefined}>
      {title ? <title>{title}</title> : null}
      <use href={href} />
    </svg>
  )
}

export const extensionToIcon: Record<IconExtKey, string> = {
  'flag-de': 'icon-flag-de',
  'flag-es': 'icon-flag-es',
  'markdown': 'icon-markdown',
  'gif': 'icon-image',
  'run': 'icon-play',
  'cl': 'icon-chevron-left',
  'edit': 'icon-edit',
  'flag-gb': 'icon-flag-gb',
  'js': 'icon-js',
  'mjs': 'icon-js',
  'json': 'icon-json',
  'x': 'icon-close',
  'sh': 'icon-terminal',
  'home': 'icon-home',
  'view': 'icon-view',
  'flag-fr': 'icon-flag-fr',
  'refresh': 'icon-refresh',
  'cr': 'icon-chevron-right',
  'minus': 'icon-minus',
  'server': 'icon-server',
  'trash': 'icon-trash',
  'paste': 'icon-paste',
  'os-windows': 'icon-os-windows',
  'settings': 'icon-settings',
  'info': 'icon-info',
  'dir': 'icon-folder',
  'jpeg': 'icon-image',
  'svg': 'icon-image',
  'gz': 'icon-archive',
  'bz2': 'icon-archive',
  'shell': 'icon-terminal',
  'download': 'icon-download',
  'stop': 'icon-stop',
  'plus': 'icon-plus',
  'screenshot': 'icon-screenshot',
  'sun': 'icon-sun',
  'link': 'icon-link',
  'os-apple': 'icon-os-apple',
  'jpg': 'icon-image',
  'close': 'icon-close',
  'up': 'icon-up',
  'user': 'icon-user',
  'copy': 'icon-copy',
  'os-ubuntu': 'icon-os-ubuntu',
  'pdf': 'icon-pdf',
  'md': 'icon-markdown',
  'png': 'icon-image',
  'upload': 'icon-upload',
  'warn': 'icon-warning',
  'search': 'icon-search',
  'log': 'icon-log',
  'cfg': 'icon-settings',
  'txt': 'icon-text',
  'zip': 'icon-archive',
  'tar': 'icon-archive',
  'moon': 'icon-moon',
} as unknown as Record<IconExtKey, string>

export function iconForExtension(ext?: string) {
  if (!ext) return undefined
  return (extensionToIcon as Record<string,string>)[ext.toLowerCase()]
}

export const mimeToIcon: Record<IconMimeKey, string> = {
  'application/x-settings': 'icon-settings',
  'application/x-terminal': 'icon-terminal',
  'application/pdf': 'icon-pdf',
  'text/plain': 'icon-text',
  'application/json': 'icon-json',
  'application/x-ui': 'icon-edit',
  'application/x-directory': 'icon-folder',
  'text/markdown': 'icon-markdown',
  'image/*': 'icon-image',
  'application/zip': 'icon-archive',
  'application/javascript': 'icon-js',
  'application/octet-stream': 'icon-upload',
} as unknown as Record<IconMimeKey, string>

export function iconForMimeOrFilename(mime?: string, filename?: string) {
  // try mime exact match
  if (mime) {
    const m = (mimeToIcon as Record<string,string>)[mime]
    if (m) return m
    // try type/* fallback
    const parts = mime.split('/')
    if (parts.length === 2) {
      const star = parts[0] + '/*'
      const ms = (mimeToIcon as Record<string,string>)[star]
      if (ms) return ms
    }
  }
  // fallback to extension
  if (filename) {
    const dot = filename.lastIndexOf('.')
    if (dot >= 0 && dot < filename.length-1) {
      const ext = filename.slice(dot+1).toLowerCase()
      return iconForExtension(ext)
    }
  }
  return undefined
}
