// Generated file: icons-types.ts
// Project: mlcremote (https://github.com/mlechner911/mlcremote)
// Do not edit this file — it is generated by cmd/icon-gen
// Generated: 2026-01-17T07:16:30Z

// Generated file: icons-types.ts
// Do not edit — generated by cmd/icon-gen


export type IconExtKey =
  'bz2'|
  'cfg'|
  'cl'|
  'close'|
  'copy'|
  'cr'|
  'dir'|
  'download'|
  'edit'|
  'flag-de'|
  'flag-es'|
  'flag-fr'|
  'flag-gb'|
  'gif'|
  'gz'|
  'home'|
  'info'|
  'jpeg'|
  'jpg'|
  'js'|
  'json'|
  'link'|
  'log'|
  'markdown'|
  'md'|
  'minus'|
  'mjs'|
  'moon'|
  'os-apple'|
  'os-ubuntu'|
  'os-windows'|
  'paste'|
  'pdf'|
  'plus'|
  'png'|
  'refresh'|
  'run'|
  'screenshot'|
  'search'|
  'server'|
  'settings'|
  'sh'|
  'shell'|
  'stop'|
  'sun'|
  'svg'|
  'tar'|
  'trash'|
  'txt'|
  'up'|
  'upload'|
  'user'|
  'view'|
  'warn'|
  'x'|
  'zip'


export type IconMimeKey =
  'application/javascript'|
  'application/json'|
  'application/octet-stream'|
  'application/pdf'|
  'application/x-directory'|
  'application/x-settings'|
  'application/x-terminal'|
  'application/x-ui'|
  'application/zip'|
  'image/*'|
  'text/markdown'|
  'text/plain'

