// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/archive/list": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Lists files and directories within an archive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "List archive contents",
                "operationId": "listArchive",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative path to archive",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers.ArchiveEntry"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/check": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Verifies if the provided authentication token is valid.",
                "tags": [
                    "auth"
                ],
                "summary": "Check auth token validity",
                "operationId": "checkAuth",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/api/copy": {
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Copies a file or directory to a new location.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Copy file/directory",
                "operationId": "copyFile",
                "parameters": [
                    {
                        "description": "Copy details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.CopyRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "description": "Subscribe to filesystem changes",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Stream filesystem events",
                "responses": {
                    "200": {
                        "description": "stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/file": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Streams file content.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Download file",
                "operationId": "downloadFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Creates or overwrites a text file.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Save file",
                "operationId": "saveFile",
                "parameters": [
                    {
                        "description": "File content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.SaveRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Moves a file to trash.",
                "tags": [
                    "file"
                ],
                "summary": "Delete file",
                "operationId": "deleteFile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Deletion disabled"
                    }
                }
            }
        },
        "/api/file/section": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Reads a chunk of a file.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Read file section",
                "operationId": "getFileSection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Start offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Length to read",
                        "name": "length",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/filetype": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Returns MIME type and text/binary classification.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Detect file type",
                "operationId": "detectFileType",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.fileTypeResp"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Exchange password for auth token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_server.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/api/logs": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Returns the last 50KB of the application log.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system logs",
                "operationId": "getLogs",
                "responses": {
                    "200": {
                        "description": "Log content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Log file not found"
                    }
                }
            }
        },
        "/api/rename": {
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Renames or moves a file.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Rename file",
                "operationId": "renameFile",
                "parameters": [
                    {
                        "description": "Rename details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.RenameRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/settings": {
            "get": {
                "description": "Returns runtime-configurable settings or updates them.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get or Update frontend settings",
                "operationId": "settingsHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Returns runtime-configurable settings or updates them.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get or Update frontend settings",
                "operationId": "settingsHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/stat": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Returns file size, mode, time, and flags.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Get file metadata",
                "operationId": "getFileStat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.FileStat"
                        }
                    }
                }
            }
        },
        "/api/terminal/new": {
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Creates a new PTY session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "Create terminal session",
                "operationId": "createTerminalSession",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shell to use (bash, zsh)",
                        "name": "shell",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Working directory",
                        "name": "cwd",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/trash": {
            "delete": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Permanently delete all files in trash.",
                "tags": [
                    "trash"
                ],
                "summary": "Empty trash",
                "operationId": "emptyTrash",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Deletion disabled"
                    }
                }
            }
        },
        "/api/trash/recent": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Returns a list of files deleted during the current session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trash"
                ],
                "summary": "Get recently deleted files",
                "operationId": "getRecentTrash",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers.TrashEntry"
                            }
                        }
                    }
                }
            }
        },
        "/api/trash/restore": {
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Restores a file from trash history.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "trash"
                ],
                "summary": "Restore file from trash",
                "operationId": "restoreTrash",
                "parameters": [
                    {
                        "description": "Trash path to restore",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.RestoreRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not found"
                    },
                    "409": {
                        "description": "Destination exists"
                    }
                }
            }
        },
        "/api/tree": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Lists files and directories.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "List directory",
                "operationId": "listDirectory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative path",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Show hidden files",
                        "name": "showHidden",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handlers.dirEntry"
                            }
                        }
                    }
                }
            }
        },
        "/api/upload": {
            "post": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Upload one or more files via multipart/form-data.",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Upload files",
                "operationId": "uploadFiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target directory",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "Files to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/version": {
            "get": {
                "description": "Returns backend version and frontend compatibility info.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get version info",
                "operationId": "getVersion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the status of the server and basic system metrics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system health",
                "operationId": "getHealth",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.healthInfo"
                        }
                    }
                }
            }
        },
        "/ws/terminal": {
            "get": {
                "security": [
                    {
                        "TokenAuth": []
                    }
                ],
                "description": "Upgrade to WebSocket for terminal I/O.",
                "tags": [
                    "terminal"
                ],
                "summary": "Connect to terminal WebSocket",
                "operationId": "connectTerminalWS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handlers.ArchiveEntry": {
            "type": "object",
            "properties": {
                "isDir": {
                    "type": "boolean"
                },
                "modTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "internal_handlers.CopyRequest": {
            "type": "object",
            "properties": {
                "destPath": {
                    "type": "string"
                },
                "sourcePath": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.FileStat": {
            "type": "object",
            "properties": {
                "absPath": {
                    "type": "string"
                },
                "isBlockDevice": {
                    "type": "boolean"
                },
                "isCharDevice": {
                    "type": "boolean"
                },
                "isDir": {
                    "type": "boolean"
                },
                "isNamedPipe": {
                    "type": "boolean"
                },
                "isReadOnly": {
                    "type": "boolean"
                },
                "isRestricted": {
                    "type": "boolean"
                },
                "isSocket": {
                    "type": "boolean"
                },
                "mime": {
                    "type": "string"
                },
                "modTime": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "internal_handlers.RenameRequest": {
            "type": "object",
            "properties": {
                "newPath": {
                    "type": "string"
                },
                "oldPath": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.RestoreRequest": {
            "type": "object",
            "properties": {
                "trashPath": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.SaveRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.TrashEntry": {
            "type": "object",
            "properties": {
                "deletedAt": {
                    "type": "string"
                },
                "originalPath": {
                    "type": "string"
                },
                "trashPath": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.dirEntry": {
            "type": "object",
            "properties": {
                "isBroken": {
                    "type": "boolean"
                },
                "isDir": {
                    "type": "boolean"
                },
                "isExternal": {
                    "type": "boolean"
                },
                "isReadOnly": {
                    "description": "!canWrite",
                    "type": "boolean"
                },
                "isRestricted": {
                    "description": "!canRead || (IsDir \u0026\u0026 !canExec)",
                    "type": "boolean"
                },
                "isSymlink": {
                    "type": "boolean"
                },
                "modTime": {
                    "type": "string"
                },
                "mode": {
                    "description": "Human readable mode string",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "internal_handlers.fileTypeResp": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "isText": {
                    "type": "boolean"
                },
                "mime": {
                    "type": "string"
                }
            }
        },
        "internal_handlers.healthInfo": {
            "type": "object",
            "properties": {
                "auth_required": {
                    "type": "boolean"
                },
                "cpu_percent": {
                    "type": "number"
                },
                "distro": {
                    "type": "string"
                },
                "go_alloc_bytes": {
                    "type": "integer"
                },
                "go_num_gc": {
                    "type": "integer"
                },
                "go_sys_bytes": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "password_auth": {
                    "type": "boolean"
                },
                "pid": {
                    "type": "integer"
                },
                "proc_rss_bytes": {
                    "type": "integer"
                },
                "server_time": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "sys_mem_free_bytes": {
                    "type": "integer"
                },
                "sys_mem_total_bytes": {
                    "type": "integer"
                },
                "timezone": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_server.loginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
